export interface Member {
  id: string;
  email: string;
  name: string;
}

export interface Trip {
  id: string;
  title: string;
  destination: string;
  startDate: string;
  endDate: string;
  members: Member[];
}
/**
 * Represents the raw, structured JSON itinerary response generated by the Gemini model.
 * Match this against the schema your frontend card components parse.
 */
export interface GeminiItineraryPayload {
  destination: string;
  days: number;
  budget: number;
  travelStyle: string;
  overview?: string;
  schedule?: Array<{
    day: number;
    title: string;
    activities: Array<{
      time: string;
      activity: string;
      location?: string;
      estimatedCost?: string | number;
    }>;
  }>;
  packingList?: string[];
  tips?: string[];
}

/**
 * Represents a normalized trip entity as returned by the Trip service (MongoDB document).
 * The `_id` field is the MongoDB ObjectId, normalized from either `_id` or `id` on the raw API response.
 */
export interface TripItem {
  _id: string;              // MongoDB ObjectId (normalized from raw `_id` or `id`)
  title: string;            // Trip display name
  destination: string;      // Primary destination city
  country?: string;         // Country of the destination
  startDate: string;        // ISO date string for trip start
  endDate: string;          // ISO date string for trip end
  budget: number;           // Total budget allocation
  notes?: string;           // Optional trip notes / description
  createdAt?: string;       // Optional ISO timestamp
}

/**
 * Represents a collaborator/member on a shared trip.
 */
export interface TripMember {
  userId: string;           // The member's user ID
  memberName?: string;      // Display name as stored on the trip
  name?: string;            // Fallback display name from user profile
  email?: string;           // Member email address
  role?: string;            // Member role (e.g. "owner", "editor", "viewer")
  avatar?: string;          // Optional profile picture URL
}

/**
 * Diagnostic tracking metrics used within the telemetry overview systems.
 */
export interface SystemTelemetryMetric {
  title: string;
  value: string | number;
  description: string;
  icon: string; // Used if mapping icon lookups by string key
  color: string;
  bg: string;
}

/**
 * Runtime log entry formats for developer workspace console outputs.
 */
export interface TerminalLogStream {
  id: string;
  timestamp: string;
  type: "info" | "warn" | "error" | "cache" | "system";
  message: string;
}