import prisma from "../../config/db.js";

/**
 * Retrieves a specific itinerary variant using the composite index.
 */
export async function getItinerary(tripId: string, inputHash: string) {
  // We use the unique composite key generated by Prisma: tripId_inputHash
  return prisma.itinerary.findUnique({
    where: {
      tripId_inputHash: {
        tripId,
        inputHash
      }
    }
  });
}

/**
 * Saves or updates an itinerary variation safely using composite tracking.
 */
export async function saveItinerary(tripId: string, itinerary: any, inputHash: string) {
  const tripExists = await prisma.trip.findUnique({
    where: { id: tripId },
    select: { id: true } 
  });

  if (!tripExists) {
    throw new Error(`TRIP_NOT_FOUND: Trip with ID ${tripId} does not exist.`);
  }

  return prisma.itinerary.upsert({
    where: {
      tripId_inputHash: {
        tripId,
        inputHash
      }
    },
    update: {
      itinerary
      // inputHash is part of the unique ID selector, no need to overwrite it here
    },
    create: {
      tripId,
      inputHash,
      itinerary
    }
  });
}

/**
 * Deletes all itinerary variants associated with a single trip record.
 */
export async function deleteItinerary(tripId: string) {
  const tripExists = await prisma.trip.findUnique({
    where: { id: tripId },
    select: { id: true }
  });

  if (!tripExists) {
    throw new Error(`TRIP_NOT_FOUND: Trip with ID ${tripId} does not exist.`);
  }

  return prisma.itinerary.deleteMany({
    where: {
      tripId
    }
  });
}